# Projects {.unnumbered}

## Major Project {#sec-hw-major}

**Task**

- This major project focuses on baking all the software engineering best practices, MLOps lifecycle and holistic ML into one code base. All the objectives of the @sec-hw-minor should be there. In addition, 
    -  at dataset (aggregate) level, models are 
        - explainable
        - calibrated
        - assessed for robustness
    - at inference time, for every instance, the following are available
        - conformal predictions
        - explanations
        - trust scores

Note:

- You can choose any problem or build on the Tabular Data provided in the class. Above must be available on _major-project_ branch of your course private repo.
- Submit your proposal no later than October 20th, 2024, Friday, 13.00pm IST.  In the repo, create a _README.md_ file at the root.
- In addition to the code, you have present the project on 26th-29th November, in-class.

Due:\

Proposal Submission: \
- 11.59PM IST, Friday, 20th Oct, 2024.

Presentations:\
- 26th and 29th, Nov, 2024, in-class.

Final Submission:\
- 11.59PM IST, Friday, 29th Nov, 2024.

## Minor Project {#sec-hw-minor}

**Task**

- This minor (mini) project focuses on baking all the software engineering best practices and MLOps lifecycle into one code base
- Create a branch named _minor-project_ of your private repo.
- For the dataset including all Tranche shared on your google drive, show that, your Models, Data, and Pipelines are
    - Project Cards, Data Cards, Model Cards, MLOps Cards are populated and are data driven.
    - Code is modular, linted, and tested
    - CI/CD hooks are implemented
    - Model is deployed and available via an API.
    - Inference can be scaled
    - Model is monitored, and a new model is deployed when an opportunity or a need to redeploy is detected.
    - Right to be forgotten is enabled.
- One way to think about it is, it is is culmination of HWs up until now.

**Due by** \
11.59PM IST, Friday, 25th Oct, 2024.